FROM node:latest

WORKDIR /massurance

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]


# docker build -t massurance .
# docker run -p 5173:5173 -p 3000:3000 massurance